### Movie Review

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# Define vocabulary size
voc_size = 10000

In [5]:
# One Hot Representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[8368, 5774, 6506, 9837],
 [8368, 5774, 6506, 9922],
 [8368, 1809, 6506, 3516],
 [7685, 1920, 2392, 9653, 2287],
 [7685, 1920, 2392, 9653, 4014],
 [7011, 8368, 554, 6506, 2903],
 [1294, 480, 4211, 9653]]

In [6]:
# Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
# from tensorflow.keras.utils import pad_sequences

In [7]:
import numpy as np

In [8]:
sent_length = 5
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0 8368 5774 6506 9837]
 [   0 8368 5774 6506 9922]
 [   0 8368 1809 6506 3516]
 [7685 1920 2392 9653 2287]
 [7685 1920 2392 9653 4014]
 [7011 8368  554 6506 2903]
 [   0 1294  480 4211 9653]]


In [9]:
# Feature representation
dim = 10

In [10]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

c:\Mayura\Programming\Github_Projects\DataScience\venv\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 174ms/step


array([[[-4.7174729e-02, -7.1156397e-03,  9.4563849e-03, -5.8817379e-03,
         -4.7102716e-02, -1.0940470e-02,  7.2998516e-03,  4.4127926e-03,
          4.9294483e-02,  2.6564114e-03],
        [-8.4726214e-03,  4.7785413e-02,  4.9615614e-03,  1.2513075e-02,
          2.0160463e-02, -2.1654153e-02, -3.2428790e-02, -3.3919990e-02,
          3.6573399e-02, -2.2074211e-02],
        [ 4.6469282e-02,  3.1117473e-02, -1.5046440e-02, -3.6481272e-02,
          1.8047336e-02, -2.5415575e-02,  4.7986332e-02, -1.6189016e-02,
          1.2684811e-02,  4.9280036e-02],
        [-2.4750603e-02, -1.2113262e-02,  2.0537470e-02, -3.6999695e-03,
          6.7935698e-03,  1.6973529e-02,  1.2043964e-02,  3.6383871e-02,
          5.6652315e-03,  3.7862871e-02],
        [-3.4643635e-03, -7.6382980e-03, -4.4731125e-03,  3.1843986e-02,
         -1.0786664e-02,  2.0366620e-02, -4.7953606e-02,  5.2861683e-03,
          1.0271348e-02,  4.7526363e-02]],

       [[-4.7174729e-02, -7.1156397e-03,  9.4563849e-03, -

In [13]:
embedded_docs[0]

array([   0, 8368, 5774, 6506, 9837], dtype=int32)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


array([[[-4.7174729e-02, -7.1156397e-03,  9.4563849e-03, -5.8817379e-03,
         -4.7102716e-02, -1.0940470e-02,  7.2998516e-03,  4.4127926e-03,
          4.9294483e-02,  2.6564114e-03],
        [-8.4726214e-03,  4.7785413e-02,  4.9615614e-03,  1.2513075e-02,
          2.0160463e-02, -2.1654153e-02, -3.2428790e-02, -3.3919990e-02,
          3.6573399e-02, -2.2074211e-02],
        [ 4.6469282e-02,  3.1117473e-02, -1.5046440e-02, -3.6481272e-02,
          1.8047336e-02, -2.5415575e-02,  4.7986332e-02, -1.6189016e-02,
          1.2684811e-02,  4.9280036e-02],
        [-2.4750603e-02, -1.2113262e-02,  2.0537470e-02, -3.6999695e-03,
          6.7935698e-03,  1.6973529e-02,  1.2043964e-02,  3.6383871e-02,
          5.6652315e-03,  3.7862871e-02],
        [-3.4643635e-03, -7.6382980e-03, -4.4731125e-03,  3.1843986e-02,
         -1.0786664e-02,  2.0366620e-02, -4.7953606e-02,  5.2861683e-03,
          1.0271348e-02,  4.7526363e-02]],

       [[-4.7174729e-02, -7.1156397e-03,  9.4563849e-03, -